# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Brewery.create(name: 'Jailbreak Brewery', address: '9445 Washington Blvd N Ste F, Laurel, MD 20723', phone: '(443) 345-9699', email: 'info@jailbreakbrewing.com', website: 'http://www.jailbreakbrewing.com/', description: 'Outdoor Beer Garden', image: 'https://pbs.twimg.com/media/EZrGmwNWAAAC8HJ.jpg')

Brewery.create(name: 'Checkerspot Brewing', address: '1399 S Sharp St, Baltimore, MD 21230', phone: '(443) 388-8912', email: '', website: 'http://www.checkerspotbrewing.com', description: 'Outdoor Patio', image: 'https://www.southbmore.com/wp-content/uploads/2019/04/IMG_9598.jpg')

Brewery.create(name: 'Monument City Brewing', address: '1 N Haven St, Baltimore, MD 21224', phone: '443) 529-8131', email: 'info@mcbrewingco.com', website: 'http://www.monumentcitybrewing.com/', description: 'Outdoor Seating', image: 'https://www.baltimoresun.com/resizer/S5AS1STBrMGmTVgZJD1JM33Pep4=/800x420/top/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/EMHZFIECRRASRLCZJEUPWZACXI.png')

Brewery.create(name: 'Diamondback Brewing', address: '1215 E Fort Ave #008, Baltimore, MD 21230', phone: '(443) 388-9419', email: 'info@diamondbackbeer.com', website: 'http://diamondbackbeer.com/', description: 'Outdoor Seating', image: 'https://media-cdn.tripadvisor.com/media/photo-s/0f/f8/4f/8e/getlstd-property-photo.jpg')

Brewery.create(name: 'Union Craft Brewing', address: '1700 W 41st St UNIT 420, Baltimore, MD 21211', phone: '(410) 467-0290', email: '', website: 'http://www.unioncraftbrewing.com/', description: 'Outdoor Beer Garden', image: 'https://www-open-maryland-gov-production.s3.amazonaws.com/media/filer_public/e6/28/e6287a01-0646-46e2-b25d-7230d3316e7e/unioncraftbrewing.jpg')

Brewery.create(name: 'Mobtown Brewing', address: '4015 Foster Ave #400, Baltimore, MD 21224', phone: '(667) 309-3653', email: 'mobtown@mobtownbrewing.com', website: 'http://www.mobtownbrewing.com/', description: 'Outdoor Seating', image: 'https://brewcruizer.com/custom/domain_1/image_files/sitemgr_photo_20142.jpg')

Brewery.create(name: 'Waverly Brewing', address: '1625 Union Ave, Baltimore, MD 21211', phone: '(443) 438-5765', email: '', website: 'http://waverlybrewingcompany.com/', description: 'Indoor', image: 'https://media-cdn.tripadvisor.com/media/photo-s/0c/f9/77/25/waverly-brewing-company.jpg')

Brewery.create(name: 'Oliver Brewing', address: '4216 Shannon Dr, Baltimore, MD 21213', phone: '', email: 'Info@Oliverbrewingco.Com', website: 'http://www.oliverbrewingco.com/', description: '', image: 'https://www.citybrewtours.com/baltimore/wp-content/uploads/sites/5/2019/04/CBTBaltimore-4488.jpg')

Brewery.create(name: 'Suspended Brewing', address: '912 Washington Blvd, Baltimore, MD 21230', phone: '(410) 926-8847', email: '', website: 'http://www.suspendedbrewing.com/', description: '', image: 'https://media-cdn.tripadvisor.com/media/photo-s/15/38/6d/ce/suspended-brewery-tavern.jpg')

Brewery.create(name: 'Peabody Heights Brewery', address: '401 E 30th St, Baltimore, MD 21218', phone: '(410) 467-7837', email: 'info@peabodyheightsbrewery.com', website: 'http://www.peabodyheightsbrewery.com/', description: 'Outdoor Patio', image: 'https://media-cdn.tripadvisor.com/media/photo-s/11/39/a8/b4/peabody-heights-tasting.jpg')

Brewery.create(name: 'Heavy Seas Brewing', address: '4615 Hollins Ferry Rd, Halethorpe, MD 21227', phone: '(410) 247-7822', email: '', website: 'http://www.hsbeer.com/', description: 'Outdoor Patio', image: 'https://www.southbmore.com/wp-content/uploads/2018/05/28109968058_5648de1a5e_z.jpg')

Brewery.create(name: 'B.C Brewing', address: '10950 Gilroy Road, Suite F, Hunt Valley, MD 21031', phone: '(443) 318-4867', email: '', website: 'https://www.bcbrewerymd.com/', description: 'Indoor', image: 'https://marylandbeer.org/wp-content/uploads/2017/09/Screen-Shot-2018-01-31-at-9.18.52-PM-300x286.png')

Brewery.create(name: 'Duclaw Brewing', address: '8901 Yellow Brick Rd ste b, Rosedale, MD 21237', phone: '(443) 559-9900', email: '', website: 'http://www.duclaw.com/', description: 'Outdoor Patio', image: 'https://www.festivalwineandspirits.com/wp-content/uploads/2016/07/DuClaw-Brewing-Company-TopImage.jpg')

Brewery.create(name: 'Pooles Island Brewing Company', address: '11695 Crossroads Cir Suite A, Middle River, MD 21220', phone: '(410) 630-9164', email: '', website: 'https://www.poolesbrewing.com/', description: 'Outdoor Seating', image: 'https://s3-media0.fl.yelpcdn.com/bphoto/6El2vdnRzMfCAoel5pm8Dg/l.jpg')

Brewery.create(name: 'Independent Brewing Company', address: '418 N Main St, Bel Air, MD 21014', phone: '(410) 937-0108', email: '', website: 'https://www.independentbrew.com/', description: 'Outdoor Patio', image: 'https://assets.downtownbelair.com/uploads/2016/10/Independent-Brewing-Co-Winner.jpg')

Brewery.create(name: 'Waredaca Brewing', address: '4017 Damascus Rd, Gaithersburg, MD 20882', phone: '(301) 774-2337', email: '', website: 'https://www.waredacabrewing.com/', description: 'Outdoor Seating', image: 'https://visitmontgomery.com/wp-content/uploads/2020/11/IMG_6230.jpeg')

Brewery.create(name: '7 locks brewing', address: '12227 Wilkins Ave, Rockville, MD 20852', phone: '(301) 841-7123', email: 'info@7locksbrewing.com', website: 'http://www.7locksbrewing.com/', description: 'Indoor', image: 'https://photos.bringfido.com/photo/2016/07/10/IMG_7750.JPG')

Brewery.create(name: 'Brookeville Beer Farm ', address: '20315 Georgia Ave, Brookeville, MD 20833', phone: '(301) 260-1000', email: 'brookevillebeerfarm@gmail.com', website: 'http://brookevillebeerfarm.com/', description: 'Outdoor Seating', image: 'https://live.staticflickr.com/4217/34216411834_274f4fbc97_b.jpg')

Brewery.create(name: 'Elder Pine Brewing', address: '4200 Sundown Rd, Gaithersburg, MD 20882', phone: '', email: 'elder@elderpine.com', website: 'https://www.elderpine.com/', description: 'Outdoor Seating', image: 'https://media-cdn.tripadvisor.com/media/photo-s/1c/7f/a3/ac/come-and-enjoy-a-pint.jpg')

Brewery.create(name: 'Saints Row Brewing', address: '1211-1213 Taft St, Rockville, MD 20850', phone: '', email: '', website: 'http://www.saintsrowbeer.com/', description: 'Outdoor Patio', image: 'https://media-cdn.tripadvisor.com/media/photo-s/1b/84/a7/20/caption.jpg')


Review.create(user_id: '1', brewery_id: '3', review: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', rating: '1')
Review.create(user_id: '1', brewery_id: '9', review: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', rating: '3')
Review.create(user_id: '1', brewery_id: '1', review: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', rating: '2')
Review.create(user_id: '1', brewery_id: '18', review: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', rating: '4')
Review.create(user_id: '1', brewery_id: '11', review: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', rating: '2')
Review.create(user_id: '1', brewery_id: '1', review: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', rating: '1')
Review.create(user_id: '1', brewery_id: '19', review: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', rating: '1')
Review.create(user_id: '1', brewery_id: '19', review: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', rating: '2')
Review.create(user_id: '1', brewery_id: '2', review: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', rating: '5')
Review.create(user_id: '1', brewery_id: '15', review: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', rating: '2')
Review.create(user_id: '1', brewery_id: '13', review: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', rating: '2')
Review.create(user_id: '1', brewery_id: '8', review: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', rating: '4')
Review.create(user_id: '1', brewery_id: '17', review: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', rating: '4')
Review.create(user_id: '1', brewery_id: '8', review: 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', rating: '4')
Review.create(user_id: '1', brewery_id: '18', review: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', rating: '3')
Review.create(user_id: '1', brewery_id: '19', review: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', rating: '3')
Review.create(user_id: '1', brewery_id: '18', review: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', rating: '5')
Review.create(user_id: '1', brewery_id: '19', review: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', rating: '2')
Review.create(user_id: '1', brewery_id: '20', review: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', rating: '4')
Review.create(user_id: '1', brewery_id: '1', review: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', rating: '2')
Review.create(user_id: '1', brewery_id: '13', review: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', rating: '4')
Review.create(user_id: '1', brewery_id: '13', review: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', rating: '4')
Review.create(user_id: '1', brewery_id: '20', review: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', rating: '2')
Review.create(user_id: '1', brewery_id: '11', review: 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', rating: '1')
Review.create(user_id: '1', brewery_id: '2', review: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', rating: '3')
Review.create(user_id: '1', brewery_id: '15', review: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', rating: '2')
Review.create(user_id: '1', brewery_id: '20', review: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', rating: '1')
Review.create(user_id: '1', brewery_id: '18', review: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', rating: '2')
Review.create(user_id: '1', brewery_id: '8', review: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', rating: '4')
Review.create(user_id: '1', brewery_id: '7', review: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', rating: '3')
Review.create(user_id: '1', brewery_id: '5', review: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', rating: '1')
Review.create(user_id: '1', brewery_id: '2', review: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', rating: '4')
Review.create(user_id: '1', brewery_id: '19', review: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', rating: '5')
Review.create(user_id: '1', brewery_id: '13', review: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', rating: '3')
Review.create(user_id: '1', brewery_id: '16', review: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', rating: '2')
Review.create(user_id: '1', brewery_id: '17', review: 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', rating: '1')
Review.create(user_id: '1', brewery_id: '14', review: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', rating: '1')
Review.create(user_id: '1', brewery_id: '1', review: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', rating: '2')
Review.create(user_id: '1', brewery_id: '7', review: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', rating: '2')
Review.create(user_id: '1', brewery_id: '15', review: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', rating: '3')
Review.create(user_id: '1', brewery_id: '15', review: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', rating: '3')
Review.create(user_id: '1', brewery_id: '7', review: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', rating: '1')
Review.create(user_id: '1', brewery_id: '14', review: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', rating: '4')
Review.create(user_id: '1', brewery_id: '15', review: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', rating: '1')
Review.create(user_id: '1', brewery_id: '14', review: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', rating: '3')
Review.create(user_id: '1', brewery_id: '12', review: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', rating: '3')
Review.create(user_id: '1', brewery_id: '9', review: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', rating: '2')
Review.create(user_id: '1', brewery_id: '6', review: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', rating: '2')
Review.create(user_id: '1', brewery_id: '15', review: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', rating: '1')
Review.create(user_id: '1', brewery_id: '5', review: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', rating: '1')
Review.create(user_id: '1', brewery_id: '1', review: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', rating: '3')
Review.create(user_id: '1', brewery_id: '8', review: 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', rating: '2')
Review.create(user_id: '1', brewery_id: '13', review: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', rating: '1')
Review.create(user_id: '1', brewery_id: '12', review: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', rating: '3')
Review.create(user_id: '1', brewery_id: '1', review: 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', rating: '3')
Review.create(user_id: '1', brewery_id: '2', review: 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', rating: '5')
Review.create(user_id: '1', brewery_id: '3', review: 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', rating: '4')
Review.create(user_id: '1', brewery_id: '16', review: 'In congue. Etiam justo. Etiam pretium iaculis justo.', rating: '4')
Review.create(user_id: '1', brewery_id: '10', review: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', rating: '1')
Review.create(user_id: '1', brewery_id: '10', review: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', rating: '4')
Review.create(user_id: '1', brewery_id: '16', review: 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', rating: '4')
Review.create(user_id: '1', brewery_id: '19', review: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', rating: '1')
Review.create(user_id: '1', brewery_id: '2', review: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', rating: '3')
Review.create(user_id: '1', brewery_id: '16', review: 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', rating: '2')
Review.create(user_id: '1', brewery_id: '2', review: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', rating: '3')
Review.create(user_id: '1', brewery_id: '19', review: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', rating: '2')
Review.create(user_id: '1', brewery_id: '15', review: 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', rating: '2')
Review.create(user_id: '1', brewery_id: '3', review: 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', rating: '5')
Review.create(user_id: '1', brewery_id: '13', review: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', rating: '3')
Review.create(user_id: '1', brewery_id: '14', review: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', rating: '4')
Review.create(user_id: '1', brewery_id: '17', review: 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', rating: '4')
Review.create(user_id: '1', brewery_id: '14', review: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', rating: '4')
Review.create(user_id: '1', brewery_id: '19', review: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', rating: '3')
Review.create(user_id: '1', brewery_id: '9', review: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', rating: '1')
Review.create(user_id: '1', brewery_id: '17', review: 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', rating: '4')
Review.create(user_id: '1', brewery_id: '2', review: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', rating: '4')
Review.create(user_id: '1', brewery_id: '9', review: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', rating: '1')
Review.create(user_id: '1', brewery_id: '16', review: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', rating: '5')
Review.create(user_id: '1', brewery_id: '2', review: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', rating: '3')
Review.create(user_id: '1', brewery_id: '4', review: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', rating: '4')
Review.create(user_id: '1', brewery_id: '13', review: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', rating: '1')
Review.create(user_id: '1', brewery_id: '20', review: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', rating: '3')
Review.create(user_id: '1', brewery_id: '16', review: 'In congue. Etiam justo. Etiam pretium iaculis justo.', rating: '3')
Review.create(user_id: '1', brewery_id: '5', review: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', rating: '5')
Review.create(user_id: '1', brewery_id: '15', review: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', rating: '1')
Review.create(user_id: '1', brewery_id: '10', review: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', rating: '5')
Review.create(user_id: '1', brewery_id: '19', review: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', rating: '2')
Review.create(user_id: '1', brewery_id: '15', review: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', rating: '4')
Review.create(user_id: '1', brewery_id: '14', review: 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', rating: '5')
Review.create(user_id: '1', brewery_id: '9', review: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', rating: '2')
Review.create(user_id: '1', brewery_id: '17', review: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', rating: '2')
Review.create(user_id: '1', brewery_id: '14', review: 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', rating: '3')
Review.create(user_id: '1', brewery_id: '10', review: 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', rating: '5')
Review.create(user_id: '1', brewery_id: '7', review: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', rating: '4')
Review.create(user_id: '1', brewery_id: '18', review: 'In congue. Etiam justo. Etiam pretium iaculis justo.', rating: '3')
Review.create(user_id: '1', brewery_id: '8', review: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', rating: '1')
Review.create(user_id: '1', brewery_id: '18', review: 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', rating: '5')
Review.create(user_id: '1', brewery_id: '17', review: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', rating: '5')
Review.create(user_id: '1', brewery_id: '15', review: 'In congue. Etiam justo. Etiam pretium iaculis justo.', rating: '2')
Review.create(user_id: '1', brewery_id: '7', review: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', rating: '1')